# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16f96bc2f3b82e0dda15fb5ba156709a44d940a49be5a02704bb6fc929f09220f6ca2f3808754877afad74d17034915afd158551e48e8c8ecd6071319587c001

test:
  secret_key_base: cb449cbdb4174d70ef02b9c8bb64f32143c65faae68d288d6a1d13b2300347b11b7bdd5c3d25f7cb1905563a7c2a2e24fe9d62b825f827c1d6689c51b7c7439c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
