# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

	##### INICIO - DELETANDO TABELAS #####

	CountryContinent.delete_all
	CountryLanguage.delete_all
	CountryClimate.delete_all
	CityUniversity.delete_all
	CourseUniversity.delete_all
	PeriodUniversity.delete_all

	Schedule.delete_all
	Student.delete_all
	University.delete_all
	City.delete_all
	Country.delete_all
	Climate.delete_all
	Continent.delete_all
	Cost.delete_all
	Course.delete_all
	Language.delete_all
	Period.delete_all
	
	##### FIM - DELETANDO TABELAS #####
	


	##### INICIO - CRIANDO TABELAS #####

	Period.create!(id:1,duracao:'3 meses')
	Period.create!(id:2,duracao:'6 meses')
	Period.create!(id:3,duracao:'1 ano')
	Period.create!(id:4,duracao:'1 ano e 6 meses')
	Period.create!(id:5,duracao:'2 anos')

	Country.create!(id:1,nome:'ALEMANHA')
	Country.create!(id:2,nome:'ARGENTINA')
	Country.create!(id:3,nome:'BÉLGICA')
	Country.create!(id:4,nome:'BOLÍVIA')
	Country.create!(id:5,nome:'CANADÁ')
	Country.create!(id:6,nome:'CHILE')
	Country.create!(id:7,nome:'COLÔMBIA')
	Country.create!(id:8,nome:'ESPANHA')
	Country.create!(id:9,nome:'EUA')
	Country.create!(id:10,nome:'FRANÇA')
	Country.create!(id:11,nome:'ITÁLIA')
	Country.create!(id:12,nome:'MÉXICO')
	Country.create!(id:13,nome:'MOÇAMBIQUE')
	Country.create!(id:14,nome:'PORTUGAL')
	Country.create!(id:15,nome:'URUGUAI')
	Country.create!(id:16,nome:'CHINA')

	City.create!(id:1 ,nome:'GÖTTINGEN',country_id:1)
	City.create!(id:2 ,nome:'CÓRDOBA',country_id:2)
	City.create!(id:3 ,nome:'SANTA FÉ',country_id:2)
	City.create!(id:4 ,nome:'ROSÁRIO',country_id:2)
	City.create!(id:5 ,nome:'BUENOS AIRES',country_id:2)
	City.create!(id:6 ,nome:'LEUVEN',country_id:3)
	City.create!(id:7 ,nome:'LA PAZ',country_id:4)
	City.create!(id:8 ,nome:'EDMONTON',country_id:5)
	City.create!(id:9 ,nome:'MONTRÉAL',country_id:5)
	City.create!(id:10 ,nome:'SANTIAGO',country_id:6)
	City.create!(id:11 ,nome:'PEQUIM',country_id:16)
	City.create!(id:12 ,nome:'MEDELLIN',country_id:7)
	City.create!(id:13 ,nome:'BUCARAMANGA',country_id:7)
	City.create!(id:14 ,nome:'BOGOTÁ',country_id:7)
	City.create!(id:15 ,nome:'SEVILLA',country_id:8)
	City.create!(id:16 ,nome:'CORUNHA',country_id:8)
	City.create!(id:17 ,nome:'MURCIA',country_id:8)
	City.create!(id:18 ,nome:'SAN CRISTÓBAL DE LA LAGUNA',country_id:8)
	City.create!(id:19 ,nome:'LEÓN',country_id:8)
	City.create!(id:20 ,nome:'CÓRDOVA',country_id:8)
	City.create!(id:21 ,nome:'GRANADA',country_id:8)
	City.create!(id:22 ,nome:'MÁLAGA',country_id:8)
	City.create!(id:23 ,nome:'VIGO',country_id:8)
	City.create!(id:24 ,nome:'CLAYTON',country_id:9)
	City.create!(id:25 ,nome:'MORGANTOWN',country_id:9)
	City.create!(id:26 ,nome:'VERSAILLES',country_id:10)
	City.create!(id:27 ,nome:'GRENOBLE',country_id:10)
	City.create!(id:28 ,nome:'FLORENÇA',country_id:11)
	City.create!(id:29 ,nome:'OBREGÓN',country_id:12)
	City.create!(id:30 ,nome:'MAPUTO',country_id:13)
	City.create!(id:31 ,nome:'PONTA DELGADA',country_id:14)
	City.create!(id:32 ,nome:'PORTO',country_id:14)
	City.create!(id:33 ,nome:'LISBOA',country_id:14)
	City.create!(id:34 ,nome:'VILA REAL',country_id:14)
	City.create!(id:35 ,nome:'MONTIVIDEO',country_id:15)

	Cost.create!(id:1,custo:'ALTO')
	Cost.create!(id:2,custo:'MÉDIO')
	Cost.create!(id:3,custo:'BAIXO')

	University.create!(id:1,nome:'Georg-August-Universität Göttingen',valor:0.0,country_id:1,cost_id:2) # ALEMANHA
	University.create!(id:2,nome:'Colégio Universitário Siglo XXI',valor:0.0,country_id:2,cost_id:3) # ARGENTINA
	University.create!(id:3,nome:'ALAMFPyONAF',valor:0.0,country_id:2,cost_id:2) # ARGENTINA
	University.create!(id:4,nome:'Instituto Universitário italiano de Rosário',valor:0.0,country_id:2,cost_id:3) # ARGENTINA
	University.create!(id:5,nome:'Universidad Austral',valor:0.0,country_id:2,cost_id:3) # ARGENTINA
	University.create!(id:6,nome:'Univ. de Ciencias Empresariales y Sociales',valor:0.0,country_id:2,cost_id:2) # ARGENTINA
	University.create!(id:7,nome:'Leuven University College _KHL',valor:0.0,country_id:3,cost_id:2) # BÉLGICA
	University.create!(id:8,nome:'Universidade Mayor de San Andres',valor:0.0,country_id:4,cost_id:3) # BOLÍVIA
	University.create!(id:9,nome:'Concórdia University College of Alberta',valor:0.0,country_id:5,cost_id:2) # CANADÁ
	University.create!(id:10,nome:'CREPUQ - Universidades de Québec',valor:0.0,country_id:5,cost_id:1) # CANADÁ
	University.create!(id:11,nome:'Instituto Profissional DuocUC',valor:0.0,country_id:6,cost_id:2) # CHILE
	University.create!(id:12,nome:'Universidade de Beijing',valor:0.0,country_id:16,cost_id:1) # CHINA
	University.create!(id:13,nome:'Universidade de Medellin',valor:0.0,country_id:7,cost_id:2) # COLÔMBIA
	University.create!(id:14,nome:'Universidade Autônoma de Bucaramanga',valor:0.0,country_id:7,cost_id:3) # COLÔMBIA
	University.create!(id:15,nome:'Universidade Colegio Mayor de Cundinamarca',valor:0.0,country_id:7,cost_id:3) # COLÔMBIA
	University.create!(id:16,nome:'Universidade Santo Tomas',valor:0.0,country_id:7,cost_id:3) # COLÔMBIA
	University.create!(id:17,nome:'SEMAL - Sociedade Espanhola de Medicina do Envelhecimento e Longevidade',valor:0.0,country_id:8,cost_id:2) # ESPANHA
	University.create!(id:18,nome:'Universidade de Coruña',valor:0.0,country_id:8,cost_id:3) # ESPANHA
	University.create!(id:19,nome:'Universidade de Murcia',valor:0.0,country_id:8,cost_id:3) # ESPANHA
	University.create!(id:20,nome:'Universidade de La Laguna',valor:0.0,country_id:8,cost_id:3) # ESPANHA
	University.create!(id:21,nome:'Universidade de León',valor:0.0,country_id:8,cost_id:2) # ESPANHA
	University.create!(id:22,nome:'Universidade de Córdoba',valor:0.0,country_id:8,cost_id:2) # ESPANHA
	University.create!(id:23,nome:'Universidade de Granada',valor:0.0,country_id:8,cost_id:2) # ESPANHA
	University.create!(id:24,nome:'Universidade de Málaga',valor:0.0,country_id:8,cost_id:1) # ESPANHA
	University.create!(id:25,nome:'Universidade de Vigo',valor:0.0,country_id:8,cost_id:2) # ESPANHA
	University.create!(id:26,nome:'Concordia Seminary',valor:0.0,country_id:9,cost_id:2) # EUA
	University.create!(id:27,nome:'West Virginia University',valor:0.0,country_id:9,cost_id:2) # EUA
	University.create!(id:28,nome:'Université de Versailles Saint-Quentin-en-Yvelines',valor:0.0,country_id:10,cost_id:1) # FRANÇA
	University.create!(id:29,nome:'Universidade Wesford – Grenoble',valor:0.0,country_id:10,cost_id:2) # FRANÇA
	University.create!(id:30,nome:'Universidade de Florença',valor:0.0,country_id:11,cost_id:1) # ITÁLIA
	University.create!(id:31,nome:'ITSON - Instituto Tecnológico de Sonora',valor:0.0,country_id:12,cost_id:3) # MÉXICO
	University.create!(id:32,nome:'UEM - Universidade Eduardo Mondlane',valor:0.0,country_id:13,cost_id:3) # MOÇAMBIQUE
	University.create!(id:33,nome:'Universidade dos Açores',valor:0.0,country_id:14,cost_id:3) # PORTUGAL
	University.create!(id:34,nome:'Universidade Fernando Pessoa',valor:0.0,country_id:14,cost_id:2) # PORTUGAL
	University.create!(id:35,nome:'Universidade de Lisboa',valor:0.0,country_id:14,cost_id:1) # PORTUGAL
	University.create!(id:36,nome:'Universidade Nova Lisboa',valor:0.0,country_id:14,cost_id:2) # PORTUGAL
	University.create!(id:37,nome:'Universidade do Porto',valor:0.0,country_id:14,cost_id:1) # PORTUGAL
	University.create!(id:38,nome:'Universidade Técnica Lisboa',valor:0.0,country_id:14,cost_id:3) # PORTUGAL
	University.create!(id:39,nome:'Universidade de Trás-os-Montes e Alto Douro',valor:0.0,country_id:14,cost_id:3) # PORTUGAL
	University.create!(id:40,nome:'IUACJ - Instituto Universitario Asociación Cristiana de Jóvenes',valor:0.0,country_id:15,cost_id:3) # URUGUAI

	#Climate.create!(id:1,nome:'QUENTE')
	#Climate.create!(id:2,nome:'FRIO')
	#Climate.create!(id:3,nome:'TROPICAL')

	Climate.create!(
		id:1,
		nome:'EQUATORIAL',
		desc: 'Muito quente e úmido. Tem pouca variação térmica durante o ano, em média de 25ºC. Bastante chuva durante o ano.'
	)
	Climate.create!(
		id:2,
		nome:'TROPICAL',
		desc: 'Possui inverno seco, e o verão chuvoso.'
	)
	Climate.create!(
		id:3,
		nome:'SUBTROPICAL',
		desc: 'É mercado pela diferenciação térmica durante o ano porque tem quatro estações bem definidas.Os principais extremos de temperatura ocorrem no verão, com variação de 20ºC a 25º, e no inverno, quando os termômetros podem marcar entre 0ºC e 10ºC.'
	)
	Climate.create!(
		id:4,
		nome:'DESÉRTICO',
		desc: 'Faz uma média de 30ºC de temperatura. As chuvas são escassas, podendo haver anos em que não chegam a ocorrer.'
	)
	Climate.create!(
		id:5,
		nome:'TEMPERADO',
		desc: 'As temperaturas são moderadas.'
	)
	Climate.create!(
		id:6,
		nome:'MEDITERRÂNEO',
		desc: 'É caracterizado por invernos curtos e de temperaturas baixas, variando entre 0ºC e 15ºC. Já o verão é longo, registrando temperaturas que oscilam entre 18ºC e 25º.'
	)
	Climate.create!(
		id:7,
		nome:'SEMI-ÁRIDO',
		desc: 'Caracteriza-se pela baixa umidade e pouquíssima quantidade de chuvas. As temperaturas são altas durante quase todo o ano.'
	)
	Climate.create!(
		id:8,
		nome:'CONTINENTAL ÁRIDO',
		desc: 'Possui clima seco, tendo como característica a grande variação de temperatura entre o verão (17º) e o inverno (20º negativos).'
	)
	Climate.create!(
		id:9,
		nome:'FRIO DE MONTANHA',
		desc: 'Frio durante todo ano.'
	)
	Climate.create!(
		id:10,
		nome:'POLAR',
		desc: 'Possui temperaturas negativas mais extremas, com termômetros sempre abaixo de 0ºC, com média de 30ºC negativos e que podem cair a 50ºC negativos no inverno.'
	)

	Continent.create!(id:1,nome:'AMÉRICA DO NORTE')
	Continent.create!(id:2,nome:'AMÉRICA CENTRAL')
	Continent.create!(id:3,nome:'AMÉRICA DO SUL')
	Continent.create!(id:4,nome:'EUROPA')
	Continent.create!(id:5,nome:'ÁSIA')
	Continent.create!(id:6,nome:'ÁFRICA')
	Continent.create!(id:7,nome:'OCEANIA')

	Course.create!(id:1, nome:'ARTE')
	Course.create!(id:2, nome:'AGROPECUÁRIA')
	Course.create!(id:3, nome:'ARQUITETURA')
	Course.create!(id:4, nome:'ARTES CÊNICAS')
	Course.create!(id:5, nome:'ADM E MARKETING')
	Course.create!(id:6, nome:'AUDITORIA')
	Course.create!(id:7, nome:'ADM SERV SAUDE')
	Course.create!(id:8, nome:'ANTROPOLOGIA')
	Course.create!(id:9, nome:'ADM EMPRESAS')
	Course.create!(id:10, nome:'ARQUEOLOGIA')
	Course.create!(id:11, nome:'ADM E GESTÃO')
	Course.create!(id:12, nome:'ANTROPOLOGIA SOCIAL E CULTURAL')
	Course.create!(id:13, nome:'BIOMEDICINA')
	Course.create!(id:14, nome:'BIBLIOTECNOLOGIA')
	Course.create!(id:15, nome:'BIOQUÍMICA')
	Course.create!(id:16, nome:'BIOTECNOLOGIA')
	Course.create!(id:17, nome:'BIOLOGIA')
	Course.create!(id:18, nome:'COMUNICAÇÃO')
	Course.create!(id:19, nome:'CIÊNCIAS AGRÍCOLAS')
	Course.create!(id:20, nome:'CIÊNCIAS DA COMPUTAÇÃO')
	Course.create!(id:21, nome:'CIÊNCIAS DA EDUCAÇÃO')
	Course.create!(id:22, nome:'CIÊNCIAS POLÍTICAS')
	Course.create!(id:23, nome:'CIÊNCIAS SOCIAIS')
	Course.create!(id:24, nome:'CIÊNCIAS NATURAIS')
	Course.create!(id:25, nome:'CONTABILIDADE')
	Course.create!(id:26, nome:'CIÊNCIAS ECONÔMICAS')
	Course.create!(id:27, nome:'COMÉRCIO EXTERIOR')
	Course.create!(id:28, nome:'COM AUDIOVISUAL')
	Course.create!(id:29, nome:'CIÊNCIA DA INFORMAÇÃO')
	Course.create!(id:30, nome:'CARREIRA AUTOMOTIVA')
	Course.create!(id:31, nome:'CIÊNCIA FORENSE')
	Course.create!(id:32, nome:'CIÊNCIA DO ESPORTE')
	Course.create!(id:33, nome:'CIÊNCIAS EMPRESARIAIS')
	Course.create!(id:34, nome:'CIÊNCIA DO DESPORTO')
	Course.create!(id:35, nome:'CRIMINOLOGIA')
	Course.create!(id:36, nome:'CIÊNCIAS AMBIENTAIS')
	Course.create!(id:37, nome:'CENOGRAFIA')
	Course.create!(id:38, nome:'DIREITO')
	Course.create!(id:39, nome:'DESENHO E URBANISMO')
	Course.create!(id:40, nome:'DESIGN GRÁFICO')
	Course.create!(id:41, nome:'DESENHO PAISAGÍSTICO')
	Course.create!(id:42, nome:'ENG ELÉTRICA')
	Course.create!(id:43, nome:'EDU FÍSICA')
	Course.create!(id:44, nome:'ENFERMAGEM')
	Course.create!(id:45, nome:'ENG AGRONÔMICA')
	Course.create!(id:46, nome:'ENG AUTOMAÇÃO')
	Course.create!(id:47, nome:'ENG COMPUTAÇÃO')
	Course.create!(id:48, nome:'ENG ELETRÔNICA')
	Course.create!(id:49, nome:'ENG INDUSTRIAL')
	Course.create!(id:50, nome:'ENG MECÂNICA')
	Course.create!(id:51, nome:'ECONOMIA')
	Course.create!(id:52, nome:'ESTATÍSTICA')
	Course.create!(id:53, nome:'ENG GEOLÓGICA')
	Course.create!(id:54, nome:'ENG GEOGRÁFICA')
	Course.create!(id:55, nome:'ENG CIVIL')
	Course.create!(id:56, nome:'ELETROMECÂNICA')
	Course.create!(id:57, nome:'ENG AMBIENTAL')
	Course.create!(id:58, nome:'ENG SISTEMAS')
	Course.create!(id:59, nome:'ENG FINANCEIRA')
	Course.create!(id:60, nome:'ENG TELECOM')
	Course.create!(id:61, nome:'ENG MATERIAIS')
	Course.create!(id:62, nome:'ENG MILITAR')
	Course.create!(id:63, nome:'EDUCAÇÃO INFANTIL')
	Course.create!(id:64, nome:'ENG MERCADO')
	Course.create!(id:65, nome:'ENG MECATRÔNICA')
	Course.create!(id:66, nome:'ENG MÚSICA')
	Course.create!(id:67, nome:'EDUCAÇÃO SOCIAL')
	Course.create!(id:68, nome:'ENG MARÍTIMA E DOS TRANSPORTES')
	Course.create!(id:69, nome:'INGLÊS')
	Course.create!(id:70, nome:'ENG QUÍMICA')
	Course.create!(id:71, nome:'ESPANHOL')
	Course.create!(id:72, nome:'ENG AGRÍCOLA E RURAL')
	Course.create!(id:73, nome:'ENG CONSTRUÇÃO')
	Course.create!(id:74, nome:'ERGONOMIA')
	Course.create!(id:75, nome:'ENG FLORESTAL')
	Course.create!(id:76, nome:'FÍSICA')
	Course.create!(id:77, nome:'FILOSOFIA')
	Course.create!(id:78, nome:'FINANÇAS E MARKETING')
	Course.create!(id:79, nome:'FISIOTERAPIA')
	Course.create!(id:80, nome:'FARMÁCIA')
	Course.create!(id:81, nome:'GEOGRAFIA')
	Course.create!(id:82, nome:'GESTÃO NEGÓCIOS')
	Course.create!(id:83, nome:'GESTÃO AGRO')
	Course.create!(id:84, nome:'GESTÃO JURÍDICA')
	Course.create!(id:85, nome:'GESTÃO CONTÁBIL')
	Course.create!(id:86, nome:'GESTÃO AMBIENTAL')
	Course.create!(id:87, nome:'HIGIENE')
	Course.create!(id:88, nome:'HISTÓRIA')
	Course.create!(id:89, nome:'INFORMÁTICA')
	Course.create!(id:90, nome:'INVEST CRIMINAL')
	Course.create!(id:91, nome:'JORNALISMO')
	Course.create!(id:92, nome:'LOGÍSTICA')
	Course.create!(id:93, nome:'LÍNGUAS')
	Course.create!(id:94, nome:'LITERATURA')
	Course.create!(id:95, nome:'MATEMÁTICA')
	Course.create!(id:96, nome:'MARKETING')
	Course.create!(id:97, nome:'MEC AUTOMOTIVA')
	Course.create!(id:98, nome:'MEC INDUSTRIAL')
	Course.create!(id:99, nome:'MEDICINA')
	Course.create!(id:100, nome:'MECATRÔNICA')
	Course.create!(id:101, nome:'METEOROLOGIA')
	Course.create!(id:102, nome:'MÚSICA')
	Course.create!(id:103, nome:'NUTRIÇÃO')
	Course.create!(id:104, nome:'NEGÓCIOS INTERNACIONAIS')
	Course.create!(id:105, nome:'ODONTOLOGIA')
	Course.create!(id:106, nome:'OPTOMETRIA')
	Course.create!(id:107, nome:'OCEANOGRAFIA')
	Course.create!(id:108, nome:'PROCESS. DADOS')
	Course.create!(id:109, nome:'PROGRAMAÇÃO DE SISTEMAS')
	Course.create!(id:110, nome:'PUBLICIDADE E PROPAGANDA')
	Course.create!(id:111, nome:'PUBLICIDADE')
	Course.create!(id:112, nome:'PSICOLOGIA')
	Course.create!(id:113, nome:'PEDAGOGIA')
	Course.create!(id:114, nome:'QUÍMICA')
	Course.create!(id:115, nome:'RP')
	Course.create!(id:116, nome:'RH')
	Course.create!(id:117, nome:'RELAÇÕES TRABALHISTAS')
	Course.create!(id:118, nome:'SOCIOLOGIA')
	Course.create!(id:119, nome:'SERVIÇO SOCIAL')
	Course.create!(id:120, nome:'TEOLOGIA')
	Course.create!(id:121, nome:'TEC LAB BIOMÉTRICO')
	Course.create!(id:122, nome:'TRABALHO SOCIAL')
	Course.create!(id:123, nome:'TURISMO')
	Course.create!(id:124, nome:'TOPOGRAFIA E GEODÉSIA')
	Course.create!(id:125, nome:'TEC TELEVISÃO')
	Course.create!(id:126, nome:'TELECOMUNICAÇÕES')
	Course.create!(id:127, nome:'TEATRO')
	Course.create!(id:128, nome:'VETERINÁRIA')

	Language.create!(id:1,nome:'INGLÊS')
	Language.create!(id:2,nome:'PORTUGUÊS')
	Language.create!(id:3,nome:'ESPANHOL')
	Language.create!(id:4,nome:'BELGA')
	Language.create!(id:5,nome:'ALEMÃO')
	Language.create!(id:6,nome:'FRANCÊS')
	Language.create!(id:7,nome:'ITALIANO')
	Language.create!(id:8,nome:'MANDARIM')

	#Student.create!(id:1,nome:'PAULO',cpf:'010.142.009-30',telefone:'33130-1010',univ_origem:'PUCRS',cidade:'PORTO ALEGRE',pais:'BRASIL',endereco:'RUA A, Nº 309')

	PeriodUniversity.create!(id:1, university_id:1 ,period_id:1)
	PeriodUniversity.create!(id:2, university_id:1 ,period_id:2)
	PeriodUniversity.create!(id:3, university_id:1 ,period_id:3)
	PeriodUniversity.create!(id:4, university_id:2 ,period_id:1)
	PeriodUniversity.create!(id:5, university_id:2 ,period_id:2)
	PeriodUniversity.create!(id:6, university_id:2 ,period_id:3)
	PeriodUniversity.create!(id:7, university_id:3 ,period_id:1)
	PeriodUniversity.create!(id:8, university_id:3 ,period_id:2)
	PeriodUniversity.create!(id:9, university_id:3 ,period_id:3)
	PeriodUniversity.create!(id:10, university_id:4 ,period_id:1)
	PeriodUniversity.create!(id:11, university_id:4 ,period_id:2)
	PeriodUniversity.create!(id:12, university_id:4 ,period_id:3)
	PeriodUniversity.create!(id:13, university_id:4 ,period_id:4)
	PeriodUniversity.create!(id:14, university_id:4 ,period_id:5)
	PeriodUniversity.create!(id:15, university_id:5 ,period_id:1)
	PeriodUniversity.create!(id:16, university_id:5 ,period_id:2)
	PeriodUniversity.create!(id:17, university_id:5 ,period_id:3)
	PeriodUniversity.create!(id:18, university_id:6 ,period_id:1)
	PeriodUniversity.create!(id:19, university_id:6 ,period_id:2)
	PeriodUniversity.create!(id:20, university_id:6 ,period_id:3)
	PeriodUniversity.create!(id:21, university_id:6 ,period_id:4)
	PeriodUniversity.create!(id:22, university_id:6 ,period_id:5)
	PeriodUniversity.create!(id:23, university_id:7 ,period_id:1)
	PeriodUniversity.create!(id:24, university_id:7 ,period_id:2)
	PeriodUniversity.create!(id:25, university_id:7 ,period_id:3)
	PeriodUniversity.create!(id:26, university_id:8 ,period_id:1)
	PeriodUniversity.create!(id:27, university_id:8 ,period_id:2)
	PeriodUniversity.create!(id:28, university_id:8 ,period_id:3)
	PeriodUniversity.create!(id:29, university_id:9 ,period_id:1)
	PeriodUniversity.create!(id:30, university_id:9 ,period_id:2)
	PeriodUniversity.create!(id:31, university_id:9 ,period_id:3)
	PeriodUniversity.create!(id:32, university_id:9 ,period_id:4)
	PeriodUniversity.create!(id:33, university_id:9 ,period_id:5)
	PeriodUniversity.create!(id:34, university_id:10 ,period_id:1)
	PeriodUniversity.create!(id:35, university_id:10 ,period_id:2)
	PeriodUniversity.create!(id:36, university_id:10 ,period_id:3)
	PeriodUniversity.create!(id:37, university_id:10 ,period_id:4)
	PeriodUniversity.create!(id:38, university_id:10 ,period_id:5)
	PeriodUniversity.create!(id:39, university_id:11 ,period_id:1)
	PeriodUniversity.create!(id:40, university_id:11 ,period_id:2)
	PeriodUniversity.create!(id:41, university_id:11 ,period_id:3)
	PeriodUniversity.create!(id:42, university_id:12 ,period_id:1)
	PeriodUniversity.create!(id:43, university_id:12 ,period_id:2)
	PeriodUniversity.create!(id:44, university_id:12 ,period_id:3)
	PeriodUniversity.create!(id:45, university_id:12 ,period_id:4)
	PeriodUniversity.create!(id:46, university_id:12 ,period_id:5)
	PeriodUniversity.create!(id:47, university_id:13 ,period_id:1)
	PeriodUniversity.create!(id:48, university_id:13 ,period_id:2)
	PeriodUniversity.create!(id:49, university_id:13 ,period_id:3)
	PeriodUniversity.create!(id:50, university_id:13 ,period_id:4)
	PeriodUniversity.create!(id:51, university_id:13 ,period_id:5)
	PeriodUniversity.create!(id:52, university_id:14 ,period_id:1)
	PeriodUniversity.create!(id:53, university_id:14 ,period_id:2)
	PeriodUniversity.create!(id:54, university_id:14 ,period_id:3)
	PeriodUniversity.create!(id:55, university_id:15 ,period_id:1)
	PeriodUniversity.create!(id:56, university_id:15 ,period_id:2)
	PeriodUniversity.create!(id:57, university_id:16 ,period_id:1)
	PeriodUniversity.create!(id:58, university_id:16 ,period_id:2)
	PeriodUniversity.create!(id:59, university_id:16 ,period_id:3)
	PeriodUniversity.create!(id:60, university_id:17 ,period_id:1)
	PeriodUniversity.create!(id:61, university_id:17 ,period_id:2)
	PeriodUniversity.create!(id:62, university_id:17 ,period_id:3)
	PeriodUniversity.create!(id:63, university_id:17 ,period_id:4)
	PeriodUniversity.create!(id:64, university_id:17 ,period_id:5)
	PeriodUniversity.create!(id:65, university_id:18 ,period_id:1)
	PeriodUniversity.create!(id:66, university_id:18 ,period_id:2)
	PeriodUniversity.create!(id:67, university_id:18 ,period_id:3)
	PeriodUniversity.create!(id:68, university_id:18 ,period_id:4)
	PeriodUniversity.create!(id:69, university_id:19 ,period_id:1)
	PeriodUniversity.create!(id:70, university_id:19 ,period_id:2)
	PeriodUniversity.create!(id:71, university_id:19 ,period_id:3)
	PeriodUniversity.create!(id:72, university_id:20 ,period_id:1)
	PeriodUniversity.create!(id:73, university_id:20 ,period_id:2)
	PeriodUniversity.create!(id:74, university_id:21 ,period_id:1)
	PeriodUniversity.create!(id:75, university_id:21 ,period_id:2)
	PeriodUniversity.create!(id:76, university_id:21 ,period_id:3)
	PeriodUniversity.create!(id:77, university_id:21 ,period_id:4)
	PeriodUniversity.create!(id:78, university_id:22 ,period_id:1)
	PeriodUniversity.create!(id:79, university_id:22 ,period_id:2)
	PeriodUniversity.create!(id:80, university_id:22 ,period_id:3)
	PeriodUniversity.create!(id:81, university_id:23 ,period_id:1)
	PeriodUniversity.create!(id:82, university_id:23 ,period_id:2)
	PeriodUniversity.create!(id:83, university_id:24 ,period_id:1)
	PeriodUniversity.create!(id:84, university_id:24 ,period_id:2)
	PeriodUniversity.create!(id:85, university_id:24 ,period_id:3)
	PeriodUniversity.create!(id:86, university_id:24 ,period_id:4)
	PeriodUniversity.create!(id:87, university_id:24 ,period_id:5)
	PeriodUniversity.create!(id:88, university_id:25 ,period_id:1)
	PeriodUniversity.create!(id:89, university_id:25 ,period_id:2)
	PeriodUniversity.create!(id:90, university_id:25 ,period_id:3)
	PeriodUniversity.create!(id:91, university_id:26 ,period_id:1)
	PeriodUniversity.create!(id:92, university_id:26 ,period_id:2)
	PeriodUniversity.create!(id:93, university_id:26 ,period_id:3)
	PeriodUniversity.create!(id:94, university_id:27 ,period_id:1)
	PeriodUniversity.create!(id:95, university_id:27 ,period_id:2)
	PeriodUniversity.create!(id:96, university_id:27 ,period_id:3)
	PeriodUniversity.create!(id:97, university_id:27 ,period_id:4)
	PeriodUniversity.create!(id:98, university_id:27 ,period_id:5)
	PeriodUniversity.create!(id:99, university_id:28 ,period_id:1)
	PeriodUniversity.create!(id:100, university_id:28 ,period_id:2)
	PeriodUniversity.create!(id:101, university_id:28 ,period_id:3)
	PeriodUniversity.create!(id:102, university_id:28 ,period_id:4)
	PeriodUniversity.create!(id:103, university_id:28 ,period_id:5)
	PeriodUniversity.create!(id:104, university_id:29 ,period_id:1)
	PeriodUniversity.create!(id:105, university_id:29 ,period_id:2)
	PeriodUniversity.create!(id:106, university_id:29 ,period_id:3)
	PeriodUniversity.create!(id:107, university_id:30 ,period_id:1)
	PeriodUniversity.create!(id:108, university_id:30 ,period_id:2)
	PeriodUniversity.create!(id:109, university_id:30 ,period_id:3)
	PeriodUniversity.create!(id:110, university_id:31 ,period_id:1)
	PeriodUniversity.create!(id:111, university_id:31 ,period_id:2)
	PeriodUniversity.create!(id:112, university_id:32 ,period_id:1)
	PeriodUniversity.create!(id:113, university_id:32 ,period_id:2)
	PeriodUniversity.create!(id:114, university_id:32 ,period_id:3)
	PeriodUniversity.create!(id:115, university_id:32 ,period_id:4)
	PeriodUniversity.create!(id:116, university_id:32 ,period_id:5)
	PeriodUniversity.create!(id:117, university_id:33 ,period_id:1)
	PeriodUniversity.create!(id:118, university_id:33 ,period_id:2)
	PeriodUniversity.create!(id:119, university_id:33 ,period_id:3)
	PeriodUniversity.create!(id:120, university_id:33 ,period_id:4)
	PeriodUniversity.create!(id:121, university_id:34 ,period_id:1)
	PeriodUniversity.create!(id:122, university_id:34 ,period_id:2)
	PeriodUniversity.create!(id:123, university_id:34 ,period_id:3)
	PeriodUniversity.create!(id:124, university_id:35 ,period_id:1)
	PeriodUniversity.create!(id:125, university_id:35 ,period_id:2)
	PeriodUniversity.create!(id:126, university_id:35 ,period_id:3)
	PeriodUniversity.create!(id:127, university_id:35 ,period_id:4)
	PeriodUniversity.create!(id:128, university_id:35 ,period_id:5)
	PeriodUniversity.create!(id:129, university_id:36 ,period_id:1)
	PeriodUniversity.create!(id:130, university_id:36 ,period_id:2)
	PeriodUniversity.create!(id:131, university_id:37 ,period_id:1)
	PeriodUniversity.create!(id:132, university_id:37 ,period_id:2)
	PeriodUniversity.create!(id:133, university_id:37 ,period_id:3)
	PeriodUniversity.create!(id:134, university_id:37 ,period_id:4)
	PeriodUniversity.create!(id:135, university_id:37 ,period_id:5)
	PeriodUniversity.create!(id:136, university_id:38 ,period_id:1)
	PeriodUniversity.create!(id:137, university_id:38 ,period_id:2)
	PeriodUniversity.create!(id:138, university_id:38 ,period_id:3)
	PeriodUniversity.create!(id:139, university_id:38 ,period_id:4)
	PeriodUniversity.create!(id:140, university_id:38 ,period_id:5)
	PeriodUniversity.create!(id:141, university_id:39 ,period_id:1)
	PeriodUniversity.create!(id:142, university_id:39 ,period_id:2)
	PeriodUniversity.create!(id:143, university_id:40 ,period_id:1)
	PeriodUniversity.create!(id:144, university_id:40 ,period_id:2)
	PeriodUniversity.create!(id:145, university_id:40 ,period_id:3)
	PeriodUniversity.create!(id:146, university_id:40 ,period_id:4)



	CountryContinent.create!(id:1,country_id:1,continent_id:4)
	CountryContinent.create!(id:2,country_id:2,continent_id:3)
	CountryContinent.create!(id:3,country_id:3,continent_id:4)
	CountryContinent.create!(id:4,country_id:4,continent_id:3)
	CountryContinent.create!(id:5,country_id:5,continent_id:1)
	CountryContinent.create!(id:6,country_id:6,continent_id:3)
	CountryContinent.create!(id:7,country_id:7,continent_id:3)
	CountryContinent.create!(id:8,country_id:8,continent_id:4)
	CountryContinent.create!(id:9,country_id:9,continent_id:1)
	CountryContinent.create!(id:10,country_id:10,continent_id:4)
	CountryContinent.create!(id:11,country_id:11,continent_id:4)
	CountryContinent.create!(id:12,country_id:12,continent_id:1)
	CountryContinent.create!(id:13,country_id:13,continent_id:6)
	CountryContinent.create!(id:14,country_id:14,continent_id:4)
	CountryContinent.create!(id:15,country_id:15,continent_id:3)
	CountryContinent.create!(id:16,country_id:16,continent_id:5)



	CountryLanguage.create!(id:1,country_id:1,language_id:5)
	CountryLanguage.create!(id:2,country_id:2,language_id:3)
	CountryLanguage.create!(id:3,country_id:3,language_id:1)
	CountryLanguage.create!(id:4,country_id:3,language_id:4)
	CountryLanguage.create!(id:5,country_id:4,language_id:3)
	CountryLanguage.create!(id:6,country_id:5,language_id:1)
	CountryLanguage.create!(id:7,country_id:5,language_id:6)
	CountryLanguage.create!(id:8,country_id:6,language_id:3)
	CountryLanguage.create!(id:9,country_id:7,language_id:3)
	CountryLanguage.create!(id:10,country_id:8,language_id:3)
	CountryLanguage.create!(id:11,country_id:9,language_id:1)
	CountryLanguage.create!(id:12,country_id:10,language_id:6)
	CountryLanguage.create!(id:13,country_id:11,language_id:7)
	CountryLanguage.create!(id:14,country_id:12,language_id:3)
	CountryLanguage.create!(id:15,country_id:13,language_id:2)
	CountryLanguage.create!(id:16,country_id:14,language_id:2)
	CountryLanguage.create!(id:17,country_id:15,language_id:3)
	CountryLanguage.create!(id:18,country_id:16,language_id:1)
	CountryLanguage.create!(id:19,country_id:16,language_id:8)



	CountryClimate.create!(id:1,country_id:1,climate_id:5)
	CountryClimate.create!(id:2,country_id:2,climate_id:5)
	CountryClimate.create!(id:3,country_id:3,climate_id:2)
	CountryClimate.create!(id:4,country_id:4,climate_id:1)
	CountryClimate.create!(id:5,country_id:4,climate_id:9)
	CountryClimate.create!(id:6,country_id:5,climate_id:5)
	CountryClimate.create!(id:7,country_id:5,climate_id:9)
	CountryClimate.create!(id:8,country_id:5,climate_id:10)
	CountryClimate.create!(id:9,country_id:6,climate_id:2)
	CountryClimate.create!(id:10,country_id:6,climate_id:5)
	CountryClimate.create!(id:11,country_id:6,climate_id:6)
	CountryClimate.create!(id:12,country_id:6,climate_id:9)
	CountryClimate.create!(id:13,country_id:7,climate_id:1)
	CountryClimate.create!(id:14,country_id:7,climate_id:9)
	CountryClimate.create!(id:15,country_id:8,climate_id:6)
	CountryClimate.create!(id:16,country_id:9,climate_id:3)
	CountryClimate.create!(id:17,country_id:9,climate_id:5)
	CountryClimate.create!(id:18,country_id:9,climate_id:6)
	CountryClimate.create!(id:19,country_id:9,climate_id:7)
	CountryClimate.create!(id:20,country_id:9,climate_id:9)
	CountryClimate.create!(id:21,country_id:10,climate_id:5)
	CountryClimate.create!(id:22,country_id:10,climate_id:6)
	CountryClimate.create!(id:23,country_id:11,climate_id:5)
	CountryClimate.create!(id:24,country_id:11,climate_id:6)
	CountryClimate.create!(id:25,country_id:12,climate_id:5)
	CountryClimate.create!(id:26,country_id:12,climate_id:6)
	CountryClimate.create!(id:27,country_id:13,climate_id:2)
	CountryClimate.create!(id:28,country_id:14,climate_id:5)
	CountryClimate.create!(id:29,country_id:14,climate_id:6)
	CountryClimate.create!(id:30,country_id:15,climate_id:3)
	CountryClimate.create!(id:31,country_id:16,climate_id:7)
	CountryClimate.create!(id:32,country_id:16,climate_id:9)



	CityUniversity.create!(id:1,city_id:1,university_id:1)
	CityUniversity.create!(id:2,city_id:2,university_id:2)
	CityUniversity.create!(id:3,city_id:3,university_id:3)
	CityUniversity.create!(id:4,city_id:4,university_id:4)
	CityUniversity.create!(id:5,city_id:5,university_id:5)
	CityUniversity.create!(id:6,city_id:5,university_id:6)
	CityUniversity.create!(id:7,city_id:6,university_id:7)
	CityUniversity.create!(id:8,city_id:7,university_id:8)
	CityUniversity.create!(id:9,city_id:8,university_id:9)
	CityUniversity.create!(id:10,city_id:9,university_id:10)
	CityUniversity.create!(id:11,city_id:10,university_id:11)
	CityUniversity.create!(id:12,city_id:11,university_id:12)
	CityUniversity.create!(id:13,city_id:12,university_id:13)
	CityUniversity.create!(id:14,city_id:13,university_id:14)
	CityUniversity.create!(id:15,city_id:14,university_id:15)
	CityUniversity.create!(id:16,city_id:14,university_id:16)
	CityUniversity.create!(id:17,city_id:15,university_id:17)
	CityUniversity.create!(id:18,city_id:16,university_id:18)
	CityUniversity.create!(id:19,city_id:17,university_id:19)
	CityUniversity.create!(id:20,city_id:18,university_id:20)
	CityUniversity.create!(id:21,city_id:19,university_id:21)
	CityUniversity.create!(id:22,city_id:20,university_id:22)
	CityUniversity.create!(id:23,city_id:21,university_id:23)
	CityUniversity.create!(id:24,city_id:22,university_id:24)
	CityUniversity.create!(id:25,city_id:23,university_id:25)
	CityUniversity.create!(id:26,city_id:24,university_id:26)
	CityUniversity.create!(id:27,city_id:25,university_id:27)
	CityUniversity.create!(id:28,city_id:26,university_id:28)
	CityUniversity.create!(id:29,city_id:27,university_id:29)
	CityUniversity.create!(id:30,city_id:28,university_id:30)
	CityUniversity.create!(id:31,city_id:29,university_id:31)
	CityUniversity.create!(id:32,city_id:30,university_id:32)
	CityUniversity.create!(id:33,city_id:31,university_id:33)
	CityUniversity.create!(id:34,city_id:32,university_id:34)
	CityUniversity.create!(id:35,city_id:33,university_id:35)
	CityUniversity.create!(id:36,city_id:33,university_id:36)
	CityUniversity.create!(id:37,city_id:32,university_id:37)
	CityUniversity.create!(id:38,city_id:33,university_id:38)
	CityUniversity.create!(id:39,city_id:34,university_id:39)
	CityUniversity.create!(id:40,city_id:35,university_id:40)

	


	CourseUniversity.create!(id:1 , course_id:1 , university_id:8)
	CourseUniversity.create!(id:2 , course_id:1 , university_id:9)
	CourseUniversity.create!(id:3 , course_id:2 , university_id:8)
	CourseUniversity.create!(id:4 , course_id:2 , university_id:35)
	CourseUniversity.create!(id:5 , course_id:3 , university_id:8)
	CourseUniversity.create!(id:6 , course_id:3 , university_id:15)
	CourseUniversity.create!(id:7 , course_id:3 , university_id:18)
	CourseUniversity.create!(id:8 , course_id:3 , university_id:23)
	CourseUniversity.create!(id:9 , course_id:3 , university_id:24)
	CourseUniversity.create!(id:10 , course_id:3 , university_id:30)
	CourseUniversity.create!(id:11 , course_id:3 , university_id:13)
	CourseUniversity.create!(id:12 , course_id:4 , university_id:35)
	CourseUniversity.create!(id:13 , course_id:5 , university_id:7)
	CourseUniversity.create!(id:14 , course_id:6 , university_id:8)
	CourseUniversity.create!(id:15 , course_id:7 , university_id:3)
	CourseUniversity.create!(id:16 , course_id:8 , university_id:10)
	CourseUniversity.create!(id:17 , course_id:8 , university_id:27)
	CourseUniversity.create!(id:18 , course_id:9 , university_id:38)
	CourseUniversity.create!(id:19 , course_id:9 , university_id:21)
	CourseUniversity.create!(id:20 , course_id:9 , university_id:12)
	CourseUniversity.create!(id:21 , course_id:9 , university_id:1)
	CourseUniversity.create!(id:22 , course_id:9 , university_id:2)
	CourseUniversity.create!(id:23 , course_id:9 , university_id:5)
	CourseUniversity.create!(id:24 , course_id:9 , university_id:34)
	CourseUniversity.create!(id:25 , course_id:9 , university_id:35)
	CourseUniversity.create!(id:26 , course_id:9 , university_id:27)
	CourseUniversity.create!(id:27 , course_id:9 , university_id:40)
	CourseUniversity.create!(id:28 , course_id:10 , university_id:33)
	CourseUniversity.create!(id:29 , course_id:10 , university_id:18)
	CourseUniversity.create!(id:30 , course_id:10 , university_id:20)
	CourseUniversity.create!(id:31 , course_id:11 , university_id:40)
	CourseUniversity.create!(id:32 , course_id:11 , university_id:21)
	CourseUniversity.create!(id:33 , course_id:11 , university_id:12)
	CourseUniversity.create!(id:34 , course_id:12 , university_id:12)
	CourseUniversity.create!(id:35 , course_id:13 , university_id:27)
	CourseUniversity.create!(id:36 , course_id:13 , university_id:19)
	CourseUniversity.create!(id:37 , course_id:13 , university_id:35)
	CourseUniversity.create!(id:38 , course_id:14 , university_id:27)
	CourseUniversity.create!(id:39 , course_id:15 , university_id:27)
	CourseUniversity.create!(id:40 , course_id:16 , university_id:31)
	CourseUniversity.create!(id:41 , course_id:17 , university_id:1)
	CourseUniversity.create!(id:42 , course_id:17 , university_id:3)
	CourseUniversity.create!(id:43 , course_id:17 , university_id:5)
	CourseUniversity.create!(id:44 , course_id:17 , university_id:10)
	CourseUniversity.create!(id:45 , course_id:17 , university_id:18)
	CourseUniversity.create!(id:46 , course_id:17 , university_id:19)
	CourseUniversity.create!(id:47 , course_id:17 , university_id:25)
	CourseUniversity.create!(id:48 , course_id:17 , university_id:27)
	CourseUniversity.create!(id:49 , course_id:17 , university_id:35)
	CourseUniversity.create!(id:50 , course_id:17 , university_id:38)
	CourseUniversity.create!(id:51 , course_id:18 , university_id:1)
	CourseUniversity.create!(id:52 , course_id:18 , university_id:4)
	CourseUniversity.create!(id:53 , course_id:18 , university_id:6)
	CourseUniversity.create!(id:54 , course_id:18 , university_id:15)
	CourseUniversity.create!(id:55 , course_id:18 , university_id:24)
	CourseUniversity.create!(id:56 , course_id:18 , university_id:27)
	CourseUniversity.create!(id:57 , course_id:18 , university_id:32)
	CourseUniversity.create!(id:58 , course_id:18 , university_id:38)
	CourseUniversity.create!(id:59 , course_id:19 , university_id:26)
	CourseUniversity.create!(id:60 , course_id:20 , university_id:8)
	CourseUniversity.create!(id:61 , course_id:20 , university_id:27)
	CourseUniversity.create!(id:62 , course_id:20 , university_id:31)
	CourseUniversity.create!(id:63 , course_id:20 , university_id:23)
	CourseUniversity.create!(id:64 , course_id:20 , university_id:35)
	CourseUniversity.create!(id:65 , course_id:21 , university_id:26)
	CourseUniversity.create!(id:66 , course_id:22 , university_id:29)
	CourseUniversity.create!(id:67 , course_id:22 , university_id:3)
	CourseUniversity.create!(id:68 , course_id:22 , university_id:2)
	CourseUniversity.create!(id:69 , course_id:23 , university_id:15)
	CourseUniversity.create!(id:70 , course_id:23 , university_id:17)
	CourseUniversity.create!(id:71 , course_id:23 , university_id:11)
	CourseUniversity.create!(id:72 , course_id:23 , university_id:10)
	CourseUniversity.create!(id:73 , course_id:24 , university_id:10)
	CourseUniversity.create!(id:74 , course_id:25 , university_id:1)
	CourseUniversity.create!(id:75 , course_id:25 , university_id:27)
	CourseUniversity.create!(id:76 , course_id:25 , university_id:35)
	CourseUniversity.create!(id:77 , course_id:25 , university_id:11)
	CourseUniversity.create!(id:78 , course_id:25 , university_id:18)
	CourseUniversity.create!(id:79 , course_id:25 , university_id:22)
	CourseUniversity.create!(id:80 , course_id:25 , university_id:29)
	CourseUniversity.create!(id:81 , course_id:25 , university_id:36)
	CourseUniversity.create!(id:82 , course_id:25 , university_id:40)
	CourseUniversity.create!(id:83 , course_id:26 , university_id:9)
	CourseUniversity.create!(id:84 , course_id:27 , university_id:3)
	CourseUniversity.create!(id:85 , course_id:27 , university_id:30)
	CourseUniversity.create!(id:86 , course_id:27 , university_id:5)
	CourseUniversity.create!(id:87 , course_id:27 , university_id:4)
	CourseUniversity.create!(id:88 , course_id:27 , university_id:9)
	CourseUniversity.create!(id:89 , course_id:27 , university_id:13)
	CourseUniversity.create!(id:90 , course_id:27 , university_id:12)
	CourseUniversity.create!(id:91 , course_id:27 , university_id:19)
	CourseUniversity.create!(id:92 , course_id:27 , university_id:21)
	CourseUniversity.create!(id:93 , course_id:27 , university_id:22)
	CourseUniversity.create!(id:94 , course_id:27 , university_id:30)
	CourseUniversity.create!(id:95 , course_id:27 , university_id:35)
	CourseUniversity.create!(id:96 , course_id:27 , university_id:38)
	CourseUniversity.create!(id:97 , course_id:27 , university_id:1)
	CourseUniversity.create!(id:98 , course_id:27 , university_id:2)
	CourseUniversity.create!(id:99 , course_id:27 , university_id:24)
	CourseUniversity.create!(id:100 , course_id:28 , university_id:20)
	CourseUniversity.create!(id:101 , course_id:28 , university_id:7)
	CourseUniversity.create!(id:102 , course_id:29 , university_id:9)
	CourseUniversity.create!(id:103 , course_id:29 , university_id:27)
	CourseUniversity.create!(id:104 , course_id:30 , university_id:40)
	CourseUniversity.create!(id:105 , course_id:30 , university_id:39)
	CourseUniversity.create!(id:106 , course_id:30 , university_id:14)
	CourseUniversity.create!(id:107 , course_id:30 , university_id:5)
	CourseUniversity.create!(id:108 , course_id:31 , university_id:40)
	CourseUniversity.create!(id:109 , course_id:31 , university_id:27)
	CourseUniversity.create!(id:110 , course_id:31 , university_id:28)
	CourseUniversity.create!(id:111 , course_id:32 , university_id:9)
	CourseUniversity.create!(id:112 , course_id:33 , university_id:4)
	CourseUniversity.create!(id:113 , course_id:33 , university_id:9)
	CourseUniversity.create!(id:114 , course_id:33 , university_id:15)
	CourseUniversity.create!(id:115 , course_id:34 , university_id:17)
	CourseUniversity.create!(id:116 , course_id:35 , university_id:39)
	CourseUniversity.create!(id:117 , course_id:36 , university_id:35)
	CourseUniversity.create!(id:118 , course_id:36 , university_id:8)
	CourseUniversity.create!(id:119 , course_id:36 , university_id:13)
	CourseUniversity.create!(id:120 , course_id:37 , university_id:12)
	CourseUniversity.create!(id:121 , course_id:38 , university_id:10)
	CourseUniversity.create!(id:122 , course_id:38 , university_id:4)
	CourseUniversity.create!(id:123 , course_id:38 , university_id:10)
	CourseUniversity.create!(id:124 , course_id:38 , university_id:31)
	CourseUniversity.create!(id:125 , course_id:39 , university_id:37)
	CourseUniversity.create!(id:126 , course_id:39 , university_id:3)
	CourseUniversity.create!(id:127 , course_id:39 , university_id:2)
	CourseUniversity.create!(id:128 , course_id:39 , university_id:8)
	CourseUniversity.create!(id:129, course_id:40 , university_id:27)
	CourseUniversity.create!(id:130 , course_id:40 , university_id:5)
	CourseUniversity.create!(id:131 , course_id:40 , university_id:15)
	CourseUniversity.create!(id:132 , course_id:40 , university_id:14)
	CourseUniversity.create!(id:133 , course_id:40 , university_id:23)
	CourseUniversity.create!(id:134 , course_id:40 , university_id:25)
	CourseUniversity.create!(id:135 , course_id:40 , university_id:27)
	CourseUniversity.create!(id:136 , course_id:40 , university_id:31)
	CourseUniversity.create!(id:137 , course_id:40 , university_id:32)
	CourseUniversity.create!(id:138 , course_id:40 , university_id:34)
	CourseUniversity.create!(id:139 , course_id:40 , university_id:35)
	CourseUniversity.create!(id:140 , course_id:40 , university_id:38)
	CourseUniversity.create!(id:141 , course_id:41 , university_id:40)
	CourseUniversity.create!(id:142 , course_id:42 , university_id:24)
	CourseUniversity.create!(id:143 , course_id:42 , university_id:1)
	CourseUniversity.create!(id:144 , course_id:42 , university_id:3)
	CourseUniversity.create!(id:145 , course_id:42 , university_id:11)
	CourseUniversity.create!(id:146 , course_id:42 , university_id:13)
	CourseUniversity.create!(id:147 , course_id:42 , university_id:18)
	CourseUniversity.create!(id:148 , course_id:42 , university_id:23)
	CourseUniversity.create!(id:149 , course_id:42 , university_id:26)
	CourseUniversity.create!(id:150 , course_id:42 , university_id:27)
	CourseUniversity.create!(id:151 , course_id:42 , university_id:30)
	CourseUniversity.create!(id:152 , course_id:42 , university_id:32)
	CourseUniversity.create!(id:153 , course_id:42 , university_id:35)
	CourseUniversity.create!(id:154 , course_id:42 , university_id:36)
	CourseUniversity.create!(id:155 , course_id:42 , university_id:38)
	CourseUniversity.create!(id:156 , course_id:43 , university_id:40)
	CourseUniversity.create!(id:157 , course_id:43 , university_id:2)
	CourseUniversity.create!(id:158 , course_id:43 , university_id:9)
	CourseUniversity.create!(id:159 , course_id:43 , university_id:13)
	CourseUniversity.create!(id:160 , course_id:43 , university_id:17)
	CourseUniversity.create!(id:161 , course_id:43 , university_id:21)
	CourseUniversity.create!(id:162 , course_id:43 , university_id:23)
	CourseUniversity.create!(id:163 , course_id:43 , university_id:27)
	CourseUniversity.create!(id:164 , course_id:43 , university_id:28)
	CourseUniversity.create!(id:165 , course_id:43 , university_id:32)
	CourseUniversity.create!(id:166 , course_id:44 , university_id:29)
	CourseUniversity.create!(id:167 , course_id:44 , university_id:7)
	CourseUniversity.create!(id:168 , course_id:45 , university_id:8)
	CourseUniversity.create!(id:169 , course_id:45 , university_id:9)
	CourseUniversity.create!(id:170 , course_id:45 , university_id:19)
	CourseUniversity.create!(id:171 , course_id:46 , university_id:22)
	CourseUniversity.create!(id:172 , course_id:46 , university_id:22)
	CourseUniversity.create!(id:173 , course_id:47 , university_id:3)
	CourseUniversity.create!(id:174 , course_id:47 , university_id:3)
	CourseUniversity.create!(id:175 , course_id:47 , university_id:4)
	CourseUniversity.create!(id:176 , course_id:47 , university_id:11)
	CourseUniversity.create!(id:177 , course_id:47 , university_id:15)
	CourseUniversity.create!(id:178 , course_id:47 , university_id:17)
	CourseUniversity.create!(id:179 , course_id:47 , university_id:20)
	CourseUniversity.create!(id:180 , course_id:48 , university_id:29)
	CourseUniversity.create!(id:181 , course_id:48 , university_id:1)
	CourseUniversity.create!(id:182 , course_id:48 , university_id:6)
	CourseUniversity.create!(id:183 , course_id:48 , university_id:4)
	CourseUniversity.create!(id:184 , course_id:48 , university_id:12)
	CourseUniversity.create!(id:185 , course_id:48 , university_id:40)
	CourseUniversity.create!(id:186 , course_id:49 , university_id:37)
	CourseUniversity.create!(id:187 , course_id:49 , university_id:35)
	CourseUniversity.create!(id:188 , course_id:49 , university_id:36)
	CourseUniversity.create!(id:189 , course_id:49 , university_id:10)
	CourseUniversity.create!(id:190 , course_id:50 , university_id:27)
	CourseUniversity.create!(id:191 , course_id:50 , university_id:27)
	CourseUniversity.create!(id:192 , course_id:50 , university_id:3)
	CourseUniversity.create!(id:193 , course_id:50 , university_id:5)
	CourseUniversity.create!(id:194 , course_id:51 , university_id:12)
	CourseUniversity.create!(id:195 , course_id:51 , university_id:16)
	CourseUniversity.create!(id:196 , course_id:51 , university_id:27)
	CourseUniversity.create!(id:197 , course_id:51 , university_id:16)
	CourseUniversity.create!(id:198 , course_id:51 , university_id:27)
	CourseUniversity.create!(id:199 , course_id:51 , university_id:23)
	CourseUniversity.create!(id:200 , course_id:52 , university_id:25)
	CourseUniversity.create!(id:201 , course_id:53 , university_id:4)
	CourseUniversity.create!(id:202 , course_id:54 , university_id:10)
	CourseUniversity.create!(id:203 , course_id:55 , university_id:10)
	CourseUniversity.create!(id:204 , course_id:55 , university_id:13)
	CourseUniversity.create!(id:205 , course_id:56 , university_id:1)
	CourseUniversity.create!(id:206 , course_id:56 , university_id:25)
	CourseUniversity.create!(id:207 , course_id:57 , university_id:16)
	CourseUniversity.create!(id:208 , course_id:57 , university_id:2)
	CourseUniversity.create!(id:209 , course_id:57 , university_id:27)
	CourseUniversity.create!(id:210 , course_id:58 , university_id:31)
	CourseUniversity.create!(id:211 , course_id:58 , university_id:38)
	CourseUniversity.create!(id:212 , course_id:59 , university_id:35)
	CourseUniversity.create!(id:213 , course_id:59 , university_id:27)
	CourseUniversity.create!(id:214 , course_id:59 , university_id:31)
	CourseUniversity.create!(id:215 , course_id:60 , university_id:18)
	CourseUniversity.create!(id:216 , course_id:61 , university_id:13)
	CourseUniversity.create!(id:217 , course_id:62 , university_id:3)
	CourseUniversity.create!(id:218 , course_id:63 , university_id:13)
	CourseUniversity.create!(id:219 , course_id:63 , university_id:27)
	CourseUniversity.create!(id:220 , course_id:63 , university_id:9)
	CourseUniversity.create!(id:221 , course_id:64 , university_id:8)
	CourseUniversity.create!(id:222 , course_id:65 , university_id:4)
	CourseUniversity.create!(id:223 , course_id:66 , university_id:18)
	CourseUniversity.create!(id:224 , course_id:67 , university_id:26)
	CourseUniversity.create!(id:225 , course_id:68 , university_id:40)
	CourseUniversity.create!(id:226 , course_id:69 , university_id:40)
	CourseUniversity.create!(id:227 , course_id:69 , university_id:15)
	CourseUniversity.create!(id:228 , course_id:69 , university_id:1)
	CourseUniversity.create!(id:229 , course_id:69 , university_id:9)
	CourseUniversity.create!(id:230 , course_id:70 , university_id:3)
	CourseUniversity.create!(id:231 , course_id:71 , university_id:5)
	CourseUniversity.create!(id:232 , course_id:71 , university_id:10)
	CourseUniversity.create!(id:233 , course_id:71 , university_id:13)
	CourseUniversity.create!(id:234 , course_id:72 , university_id:18)
	CourseUniversity.create!(id:235 , course_id:73 , university_id:35)
	CourseUniversity.create!(id:236 , course_id:74 , university_id:30)
	CourseUniversity.create!(id:237 , course_id:75 , university_id:17)
	CourseUniversity.create!(id:238 , course_id:76 , university_id:27)
	CourseUniversity.create!(id:239 , course_id:76 , university_id:9)
	CourseUniversity.create!(id:240 , course_id:77 , university_id:27)
	CourseUniversity.create!(id:241 , course_id:77 , university_id:20)
	CourseUniversity.create!(id:242 , course_id:77 , university_id:19)
	CourseUniversity.create!(id:243 , course_id:78 , university_id:27)
	CourseUniversity.create!(id:244 , course_id:78 , university_id:13)
	CourseUniversity.create!(id:245 , course_id:78 , university_id:34)
	CourseUniversity.create!(id:246 , course_id:79 , university_id:35)
	CourseUniversity.create!(id:247 , course_id:80 , university_id:1)
	CourseUniversity.create!(id:248 , course_id:80 , university_id:6)
	CourseUniversity.create!(id:249 , course_id:81 , university_id:6)
	CourseUniversity.create!(id:250 , course_id:81 , university_id:23)
	CourseUniversity.create!(id:251 , course_id:81 , university_id:27)
	CourseUniversity.create!(id:252 , course_id:82 , university_id:1)
	CourseUniversity.create!(id:253 , course_id:83 , university_id:10)
	CourseUniversity.create!(id:254 , course_id:84 , university_id:19)
	CourseUniversity.create!(id:255 , course_id:85 , university_id:10)
	CourseUniversity.create!(id:256 , course_id:86 , university_id:15)
	CourseUniversity.create!(id:257 , course_id:87 , university_id:13)
	CourseUniversity.create!(id:258 , course_id:88 , university_id:1)
	CourseUniversity.create!(id:259 , course_id:88 , university_id:3)
	CourseUniversity.create!(id:260 , course_id:88 , university_id:27)
	CourseUniversity.create!(id:261 , course_id:89 , university_id:38)
	CourseUniversity.create!(id:262 , course_id:89 , university_id:31)
	CourseUniversity.create!(id:263 , course_id:89 , university_id:27)
	CourseUniversity.create!(id:264 , course_id:89 , university_id:17)
	CourseUniversity.create!(id:265 , course_id:89 , university_id:11)
	CourseUniversity.create!(id:266 , course_id:89 , university_id:35)
	CourseUniversity.create!(id:267 , course_id:90 , university_id:5)
	CourseUniversity.create!(id:268 , course_id:91 , university_id:8)
	CourseUniversity.create!(id:269 , course_id:92 , university_id:13)
	CourseUniversity.create!(id:270 , course_id:93 , university_id:13)
	CourseUniversity.create!(id:271 , course_id:93 , university_id:27)
	CourseUniversity.create!(id:272 , course_id:93 , university_id:5)
	CourseUniversity.create!(id:273 , course_id:93 , university_id:24)
	CourseUniversity.create!(id:274 , course_id:94 , university_id:20)
	CourseUniversity.create!(id:275 , course_id:95 , university_id:18)
	CourseUniversity.create!(id:276 , course_id:95 , university_id:27)
	CourseUniversity.create!(id:277 , course_id:95 , university_id:32)
	CourseUniversity.create!(id:278 , course_id:96 , university_id:6)
	CourseUniversity.create!(id:279 , course_id:96 , university_id:14)
	CourseUniversity.create!(id:280 , course_id:96 , university_id:15)
	CourseUniversity.create!(id:281 , course_id:97 , university_id:13)
	CourseUniversity.create!(id:282 , course_id:98 , university_id:15)
	CourseUniversity.create!(id:283 , course_id:99 , university_id:24)
	CourseUniversity.create!(id:284 , course_id:99 , university_id:1)
	CourseUniversity.create!(id:285 , course_id:99 , university_id:31)
	CourseUniversity.create!(id:286 , course_id:99 , university_id:29)
	CourseUniversity.create!(id:287 , course_id:99 , university_id:13)
	CourseUniversity.create!(id:288 , course_id:99 , university_id:27)
	CourseUniversity.create!(id:289 , course_id:100 , university_id:1)
	CourseUniversity.create!(id:290 , course_id:101 , university_id:5)
	CourseUniversity.create!(id:291 , course_id:102 , university_id:8)
	CourseUniversity.create!(id:292 , course_id:103 , university_id:23)
	CourseUniversity.create!(id:293 , course_id:104 , university_id:27)
	CourseUniversity.create!(id:294 , course_id:105 , university_id:27)
	CourseUniversity.create!(id:295 , course_id:106 , university_id:27)
	CourseUniversity.create!(id:296 , course_id:107 , university_id:11)
	CourseUniversity.create!(id:297 , course_id:108 , university_id:28)
	CourseUniversity.create!(id:298 , course_id:109 , university_id:35)
	CourseUniversity.create!(id:299 , course_id:110 , university_id:12)
	CourseUniversity.create!(id:300 , course_id:111 , university_id:40)
	CourseUniversity.create!(id:301 , course_id:111 , university_id:9)
	CourseUniversity.create!(id:302 , course_id:111 , university_id:28)
	CourseUniversity.create!(id:303 , course_id:112 , university_id:20)
	CourseUniversity.create!(id:304 , course_id:112 , university_id:1)
	CourseUniversity.create!(id:305 , course_id:113 , university_id:3)
	CourseUniversity.create!(id:306 , course_id:114 , university_id:2)
	CourseUniversity.create!(id:307 , course_id:115 , university_id:27)
	CourseUniversity.create!(id:308 , course_id:116 , university_id:10)
	CourseUniversity.create!(id:309 , course_id:117 , university_id:1)
	CourseUniversity.create!(id:310 , course_id:118 , university_id:40)
	CourseUniversity.create!(id:311 , course_id:119 , university_id:1)
	CourseUniversity.create!(id:312 , course_id:120 , university_id:27)
	CourseUniversity.create!(id:313 , course_id:121 , university_id:32)
	CourseUniversity.create!(id:314 , course_id:122 , university_id:33)
	CourseUniversity.create!(id:315 , course_id:123 , university_id:6)
	CourseUniversity.create!(id:316 , course_id:124 , university_id:18)
	CourseUniversity.create!(id:317 , course_id:125 , university_id:10)
	CourseUniversity.create!(id:318 , course_id:126 , university_id:13)
	CourseUniversity.create!(id:319 , course_id:127 , university_id:31)
	CourseUniversity.create!(id:320 , course_id:128 , university_id:20)

	##### FIM - CRIANDO TABELAS #####